apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-dns-monitor
  labels:
    {{- include "k8s-dns-monitor.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - apps
  resources:
    - pods
    - services
    - nodes
    - namespaces
    - deployments
  verbs:
    - list
    - get
    - create
    - delete
    - update
    - patch