apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-dns-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-dns-monitor.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: {{ .Values.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
  selector:
    {{- include "k8s-dns-monitor.selectorLabels" . | nindent 4 }}